# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skintype',
            field=models.CharField(default='combination', max_length=30),
        ),
    ]
