# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_auto_20180224_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('productType', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('users', models.ManyToManyField(to='skincare.Profile')),
            ],
        ),
    ]
